export const GET_ORDERS_REQUEST = 'GET_ORDERS_REQUEST';
export const GET_ORDERS_SUCCESS = 'GET_ORDERS_SUCCESS';
export const GET_ORDERS_FAILURE = 'GET_ORDERS_FAILURE';

export const CONFIRMED_ORDER_REQUEST = 'CONFIRMED_ORDER_REQUEST';
export const CONFIRMED_ORDER_SUCCESS = 'CONFIRMED_ORDER_SUCCESS';
export const CONFIRMED_ORDER_FAILURE = 'CONFIRMED_ORDER_FAILURE';

export const PLACED_ORDER_REQUEST = 'PLACED_ORDER_REQUEST';
export const PLACED_ORDER_SUCCESS = 'PLACED_ORDER_SUCCESS';
export const PLACED_ORDER_FAILURE = 'PLACED_ORDER_FAILURE';

export const DELIVERED_ORDERS_REQUEST = 'DELIVERED_ORDERS_REQUEST';
export const DELIVERED_ORDERS_SUCCESS = 'DELIVERED_ORDERS_SUCCESS';
export const DELIVERED_ORDERS_FAILURE = 'DELIVERED_ORDERS_FAILURE';

export const CANCELED_ORDERS_REQUEST = 'CANCELED_ORDERS_REQUEST';
export const CANCELED_ORDERS_SUCCESS = 'CANCELED_ORDERS_SUCCESS';
export const CANCELED_ORDERS_FAILURE = 'CANCELED_ORDERS_FAILURE';

export const DELETE_ORDERS_REQUEST = 'DELETE_ORDERS_REQUEST';
export const DELETE_ORDERS_SUCCESS = 'DELETE_ORDERS_SUCCESS';
export const DELETE_ORDERS_FAILURE = 'DELETE_ORDERS_FAILURE';


export const SHIP_ORDERS_REQUEST = 'SHIP_ORDERS_REQUEST';
export const SHIP_ORDERS_SUCCESS = 'SHIP_ORDERS_SUCCESS';
export const SHIP_ORDERS_FAILURE = 'SHIP_ORDERS_FAILURE';